# ===========
# CONFIG FILE
# ===========
#
# method
method: <METHOD>  # no-da, mmd, dat, ynet, wnet or unet-ts
lambda_mmd: <LAMBDA_MMD>
lambda_dat: <LAMBDA_DAT>
lambda_rec: <LAMBDA_REC>
lambda_o: <LAMBDA_O>
lambda_w: <LAMBDA_W>
# data
src:
  data: /home/jorisro/research/data/EM/<DOMAIN>/raw
  labels: /home/jorisro/research/data/EM/<DOMAIN>/labels
  train_val_test_split: <TRAIN_VAL_TEST_SPLIT>
  split_orientation: <SPLIT_ORIENTATION>
tar:
  data: /home/jorisro/research/data/EM/<DOMAIN>/raw
  labels: /home/jorisro/research/data/EM/<DOMAIN>/labels
  train_val_test_split: <TRAIN_VAL_TEST_SPLIT>
  split_orientation: <SPLIT_ORIENTATION>
type: pngseq
augmentation: rot90,flipx,flipy,contrast,noise
tar_labels_available: <AVAILABLE_LABELS>
# network
input_size: <INPUT_SIZE>
in_channels: 1
fm: 16
levels: 4
dropout: <DROPOUT>
norm: batch
activation: relu
coi: <COI>
# optimization
loss: dice
lr: 0.001
epochs: 200
len_epoch: 2000
train_batch_size: 4
test_batch_size: 4
# compute
gpus: <GPU>
num_workers: 12
accelerator: dp
# logging
log_dir: /home/jorisro/research/domain-adaptive-segmentation/train/gs/logs/<LOG_DIR>
log_freq: 50
log_refresh_rate: 0
# reproducibility
seed: 0

