# ===========
# CONFIG FILE
# ===========
#
# method
method: u-net  # u-net
# data
data: /home/jorisro/research/data/EM/VNC/raw
labels: /home/jorisro/research/data/EM/VNC/labels
train_val_test_split: 0.50,0.75
split_orientation: z
type: pngseq
# network
input_size: 256,256
in_channels: 1
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# optimization
loss: ce
lr: 0.001
epochs: 1
train_batch_size: 4
test_batch_size: 4
# compute
gpus: 0
num_workers: 12
accelerator: dp
# logging
log_dir: supervised
log_freq: 50
log_refresh_rate: -1
# reproducibility
seed: 0
