# ===========
# CONFIG FILE
# ===========
#
# method
method: no-da  # no-da, mmd, dat, ynet, wnet or unet-ts
lambda_mmd: 1
lambda_dat: 1
lambda_rec: 1
lambda_o: 1
lambda_w: 1
# data
src:
  data: /home/jorisro/research/data/EM/EPFL/raw
  labels: /home/jorisro/research/data/EM/EPFL/labels
  train_val_test_split: 0.50,0.75
  split_orientation: z
tar:
  data: /home/jorisro/research/data/EM/VNC/raw
  labels: /home/jorisro/research/data/EM/VNC/labels
  train_val_test_split: 0.50,0.75
  split_orientation: z
type: pngseq
augmentation: rot90,flipx,flipy,contrast,deformation,noise  # options: rot90,flipx,flipy,contrast,deformation,noise
tar_labels_available: 0.00
# network
input_size: 256,256
in_channels: 1
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# optimization
loss: dice
lr: 0.001
epochs: 5
len_epoch: 2000
train_batch_size: 4
test_batch_size: 4
# compute
gpus: 0
num_workers: 12
accelerator: dp
# logging
log_dir: semi_supervised
log_freq: 50
log_refresh_rate: -1
# reproducibility
seed: 0
